### PR TITLE
Changed API for Svenska Spel. Fixes #376

### LINKED ISSUE #376: Still cannot login to Svenska Spel!?
Just tried the last updated versions of Bankdroid (1.9.7.1 and 1.9.7.2) and I still cannot login to Svenska Spel. Still get the same error as last time, about certificate not trusted or whatever it said. Something wrong on my side, or yet another certificate update needed?

### PR DESCRIPTION
**Pull request by mikaeler**
Fixes #376

### CODE REVIEW

**Comment by goober** [comment]
@mikaeler Before I merge this, can you confirm that the fix is still working?

**Comment by mikaeler** [comment]
It is still working. I have been using it on my phone since I comitted it.

**Comment by goober** [comment]
Thank you for your contribution. Sorry for the delay.

**Comment by dobedidoo** [comment]
I still cannot add this "bank". I use v1.9.7.3 and get error message 'Server certificate not trusted for host: m.svenskaspel.se.' Tried again today.

**Comment by liato** [comment]
@dobedidoo The fix should be available in v1.9.7.4-RC1. You need to register as a beta tester (takes 10 seconds) before it's available in Google Play.
More info about becomming a beta tester is available at https://plus.google.com/communities/100653997163783123944

**Pull request merged**
