### PR TITLE
Make static code analysis cover all code

### PR DESCRIPTION
**Pull request by walles**
Before this change, there were two Java sub projects that weren't covered by the static code analysers (FindBugs, Checkstyle, Android Lint, PMD).

This change moves the code in the Java projects (it wasn't much) into the two Android projects.

I did try to get static code analysis into the Java projects as well, but that turned into a Gradle / Groovy mess I didn't manage to finish.

### CODE REVIEW

**Comment by walles** [comment]
I have verified this change by adding a new account and verifying the edit-account activity looks like it should.

**Comment by goober** [comment]
The long term goal is to move out as much logic as possible from the android modules into java modules, hence this is a change in the opposite direction. Each bank implementation should, when completed, only be dependent on the `bankdroid-interface` module. However, all modules should of course be covered by the static code analysis. 

I will try to take a look tonight if the gradle mess you mention can be sorted out somehow, without merging the current java projects. 

Please feel free to continue the discussion if you disagree.

**Comment by walles** [comment]
My point with this change was only to have the static analysis cover everything, so if there are other paths there I'm totally fine with that. Thanks for the long term plan info!

I guess there are two different ways (that are not this PR):
* Make `quality.gradle` work for Java projects as well and not just Android ones as today
* Turn `bankdroid-interface` and `bankdroid-core` into Android projects

The second one might be simpler than the first.

**Comment by goober** [comment]
Closing in favor for #645

**Pull request closed without merging**
