### PR TITLE
Support for Östgötatrafiken's travel cards.

### LINKED ISSUE #130: New bank: Östgötatrafiken
http://pastebin.com/u/pk_fms

### PR DESCRIPTION
**Pull request by robho**
This adds support for Östgötatrafiken's travel cards in bankdroid (Fixes #130).

It allows a user to view the amount of money remaining on his/her travel card(s):

bankdroid_ogt

### CODE REVIEW

**Comment by goober** [comment]
@robho If you want this pull request merged into the application can you please rebase your changes against the `master` branch so it can be merged.

**Comment by simonjosefsson** [comment]
Yes, please do! I would very much like to have ÖGT in bankdroid :+1:

**Comment by robho** [comment]
Pull request updated.

**Comment by goober** [comment]
Thank you!

**Pull request merged**
