### PR TITLE
Remove support for Avanza and Avanza mini

### PR DESCRIPTION
**Pull request by goober**
Since Avanza has removed the API that Bankdroid relies on. 
There exists a websocket api that can be used, or use the REST api from their website. But currently I have no time for updating the implementation so until then Avanza and Avanza mini should be removed.

### CODE REVIEW

**Comment by walles** [comment]
Are there any logos / icons that should be removed as well?

**Comment by goober** [comment]
Thanks, I missed those.

**Comment by robho** [comment]
.. and maybe also the certificate

**Comment by goober** [comment]
Thanks for the reminder @robho

**Pull request merged**
