### PR TITLE
Added support for Android 6.0 Marshmallow

### LINKED ISSUE #582: Add support for app-backup
For apps whose target SDK version is Android 6.0 (API level 23) and higher, devices running Android 6.0 and higher automatically back up app data to the cloud.

http://developer.android.com/training/backup/autosyncapi.html

### PR DESCRIPTION
**Pull request by fredrike**
Attempt to add support for Android-M, to fix #582 .

### CODE REVIEW

**Comment by goober** [comment]
Make sure to update https://github.com/liato/android-bankdroid/blob/master/bankdroid-legacy/build.gradle as well. I think this is why the build fails

**Comment by fredrike** [comment]
Still fails due to:

```
liato-android-bankdroid/app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java:125: error: cannot find symbol
        notification.setLatestEventInfo(context, bank.getDisplayName(), text, contentIntent);
                    ^
  symbol:   method setLatestEventInfo(Context,String,String,PendingIntent)
  location: variable notification of type Notification
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: liato-android-bankdroid/app/src/main/java/com/liato/bankdroid/BankEditActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

 FAILED
```

But now we can debug as a joint effort.

**Comment by fredrike** [comment]
Wow, compiles and looks good. 

Still needs test with the re-write of notifications.

**Comment by fredrike** [comment]
Tested and verified, notifications now works as before.

**Comment by goober** [comment]
Thanks

**Pull request merged**
