### PR TITLE
Fix Instant Run

### PR DESCRIPTION
**Pull request by walles**
This change fixes Instant Run in Android Studio 2.2.1 by upgrading the
Android Build Tools Gradle dependency (as suggested by Android Studio)
and by not storing Contexts in static variables (as suggested by
Android Lint).

### CODE REVIEW

**Comment by walles** [comment]
The failure is likely because of this bug:
https://code.google.com/p/android/issues/detail?id=194092

**Comment by walles** [comment]
Nothing helps, bug reported here:
https://code.google.com/p/android/issues/detail?id=225515

Closing for now, we'll see how that goes.

**Comment by goober** [comment]
I have tried to reproduce this locally as you suggested in the bug report, without any luck. The build succeeds locally

**Comment by walles** [comment]
Yeah, I did try `-Dlint.new-lib-model=true`, no luck :(.

Really strange that this works for you, wonder what you are (not) doing that I and Travis are?

For me this fails both locally and on Travis, same results.

**Comment by goober** [comment]
I had an old gradle daemon running. When I ran will the `--no-daemon` flag it fails for me as well

**Comment by walles** [comment]
However much I dislike saying this, as long as `UnusedResources` doesn't work we can't use it :/.

Disabling warning and squashing, please review.

**Comment by goober** [comment]
I agree with you that the proper solution is to temporary disable the `UnusedResources` for now. 
And the `update-supressions.sh` script will catch when the bug if fixed (if we do not introduce more unused resources)

**Pull request merged**
