### PR TITLE
Show warning for disabled banks

### PR DESCRIPTION
**Pull request by walles**
Before this change, in the banks list in the main UI, disabled banks
were marked with a warning icon.

This change adds to that warning icon a text describing what's actually
going on and what the user can do about it.

Before starting to work on this I fixed all Android Lint reported
warnings in the .java and .xml files I had to change, and re-enabled
those warnings.

One of those warnings was about using sp rather than dp for text. I
suppressed that warning for the widgets, but heeded it in all other
places. This results in a UI that better adapts to the user's font size
preferences.

The UI changes I have tested with both "small" and "huge" font size,
and it looks fine.

### CODE REVIEW

**Comment by walles** [comment]
skarmavbild 2016-10-20 kl 22 58 00

**Comment by walles** [comment]
Here's what the transactions list looks like with the system font size set to "Huge".

skarmavbild 2016-10-20 kl 22 58 27

**Comment by walles** [comment]
This is the last part of fixing #610.

**Comment by walles** [comment]
The XML file changes might best be reviewed ignoring whitespace:
https://github.com/blog/967-github-secrets

**Comment by goober** [comment]
I have nothing to add here. A good PR! I really appreciate that you take the time to clean up the code while your at it. Thanks!

**Pull request merged**
