### PR TITLE
Android Lint: Enforce no unused resources

### PR DESCRIPTION
**Pull request by walles**
Please review for unwanted resource removals...

### CODE REVIEW

**Comment by walles** [comment]
Thanks @robho, fixed!

**Comment by goober** [comment]
I need to checkout this PR and run it locally and do some regression testing before I can merge this. I hope it is ok.

**Comment by walles** [comment]
Sure!

My plan for this is that after this goes in I'll remove unused code, then remove unneeded Android Lint suppressions, then start to actually code on #610. #610 has UI work in it, and I want as much linter support as I can get for that...

**Comment by walles** [comment]
Also, I've found that the turnaround time for code reviews in here is amazing, and with sensible feedback, so big thanks @goober & @robho!

**Comment by goober** [comment]
I have done some testing and everything seems to work as expected. I will merge this.

**Pull request merged**
