### PR TITLE
added support for Coop's MedMera-Mer MasterCard

### PR DESCRIPTION
**Pull request by fredrike**
Coop have introduced some new cards the MedMera-Mer is one of them (I don't have the other cards so I can't add support for more than this atm).

https://www.coop.se/Betalkort-och-bank/Vara-betal--och-kreditkort/

The patch is verified and works fine.

### CODE REVIEW

**Comment by liato** [comment]
Cool, thanks!

**Comment by Chrille2k** [comment]
Perfect, just what I needed, when will this change we available on Google Play?

**Comment by liato** [comment]
@Chrille2k: haven't had time this week, I'll try to do it during the weekend.

**Comment by Chrille2k** [comment]
Wonderful! Many many thanks for this awesome app!

**Pull request merged**
