### PR TITLE
Fixed transactions for Forex, fixes #257

### LINKED ISSUE #257: Missing transactions for Forex
http://www.swedroid.se/forum/showthread.php?p=1423628#post1423628

### PR DESCRIPTION
**Pull request by jonasgroth**
Fixed problem with transactions for one of the accounts showing for all accounts.

### CODE REVIEW

**Comment by goober** [comment]
Thanks for your contribution. Could you please [squash your commits] (http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) into a single commit so the merge commits are removed? Thank you.

**Comment by fredrike** [comment]
The best is actually to checkout liato/master, create a new branch and make the commit (bb32aa5) to that.

**Comment by jonasgroth** [comment]
@goober Done!

**Comment by fredrike** [comment]
Thank you!

Sorry to be a pita but it would be great if you could add a newline to the last line as well (trying to get and keep the code clean(er)).

**Comment by jonasgroth** [comment]
@fredrike Added newline!

**Comment by fredrike** [comment]
Thank you!

**Pull request merged**
