### PR TITLE
Fix whitespace issues

### PR DESCRIPTION
**Pull request by walles**
Enable Checkstyle whitespace checks.

Ran into some violations in an earlier PR, found it was bad for readability.

### CODE REVIEW

**Comment by fredrike** [comment]
Great! But I think the removed files should be in a separate pr. 

@goober what is the purpose of the removed files?

**Comment by goober** [comment]
@fredrike I agree with you that the removed files should be a separate PR. However, I would like them to be kept for a while. I have an upcoming PR that uses some of the classes so please keep them for now. I will do a cleanup as soon as I am finished.

**Comment by walles** [comment]
I removed the files as a way to resolve whitespace errors in them; since they were unused fixing them seemed not worth any effort.

But since I need to rebase anyway I'll just put them back as part of that rebase.

**Comment by goober** [comment]
It looks good. However, it would be great if you could leave `LegacyBankHelper` as well.

**Pull request merged**
