### PR TITLE
Fail build on Android Lint problems

### PR DESCRIPTION
**Pull request by walles**
Fix one issue, disable lots of warnings to enable merging *something*
at least.

### CODE REVIEW

**Comment by walles** [comment]
The actual removal of unused resources was done by:
* Opening Android Studio
* Doing Analyze / Run Inspection by Name
* Choosing `Unused resources`
* `Whole project`
* Right clicking one of the errors
* Clicking on the fix-automatically option

**Comment by walles** [comment]
Tested that Länsförsäkringar works after these renmovals.

**Comment by goober** [comment]
I see that all logos are included in this removal.
Since bankdroid loads logo resources dynamically as seen in [Bank.java#L387](https://github.com/liato/android-bankdroid/blob/8c04fd55c6eb4f5e4688dd831dcbeaf9b5440536/bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/Bank.java#L387), it seems that the analysis does not recognize this usage. So maybe you can add an ignore pattern for the `UnusedResource` issue?

e.g.
`
  <issue id="UnusedResources">
    <ignore path="res\drawable\logo_*png" />
  </issue>
`

**Comment by walles** [comment]
Fixing `UnusedResources` seems too hard for now, this was easier.

Ready for re-review!

**Comment by goober** [comment]
I understand you :) but it is a good start! Thanks

**Pull request merged**
