### PR TITLE
Avanza patch

### PR DESCRIPTION
**Pull request by fredrike**
added support to show balance. Also, shows all sub-accounts as main accounts.

### CODE REVIEW

**Comment by goober** [comment]
Thanks

**Comment by jmbe** [comment]
@fredrike Please revert showing sub-accounts as main account (if by sub-accounts you mean the recent change that instrument types like Kassa, Aktier, Fonder, Börshandlade fonder, Obligationer, Warranter etc etc is displayed in the main view).

The Avanza "summary" is about 30 items long now, when it shows every little detail about all accounts in the main view. I wish to only see total sum for each account. If and when I want to see the different instrument types within the account I can simply click on it, like how it was before. I hope you agree that this mostly unimportant information is better displayed there.

Please consider reverting.

**Comment by fredrike** [comment]
@jmbe Wow, 30 is a lot of items. 

The items were added to enable separate widgets for each subaccount. I do think there is use for showing all accounts and sub-accounts. But I understand your concern. 

What about hiding sub-accounts by default?

You do know that you can hide accounts you are not interested in viewing?

**Comment by jmbe** [comment]
@fredrike Hiding by default sounds good! Yes, I do know about hiding, but there would be quite a lot of hiding (multiplied by number of devices), since I really only want to see my 4 main accounts (like how it was before). And if for some reason I need to re-login, then all hidden accounts return and I would need to hide them again.

It is really only about 4 active accounts, which is probably quite common (2*ISK + KF + IPS). Add credit accounts, maybe one or two inactive accounts and multiply by number of instruments per account and you reach 30+ items in summary quickly.

Hiding instrument types by default in summary sounds good. Then I could just hide the few remaining inactive accounts manually.

**Pull request merged**
